branches:
  only:
    - master

skip_tags: true
skip_non_tags: false

max_jobs: 8

image: Visual Studio 2017

init:

shallow_clone: true
clone_depth: 1

install:
  - dir C:\mingw-w64\*
  - dir C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\*
  - dir C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\bin\*
  
